name: example
description: "Presentations example."

publish_to: "none"

homepage: https://github.com/itsezlife/presentum

repository: https://github.com/itsezlife/presentum

issue_tracker: https://github.com/itsezlife/presentum/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - presentation
  - state
  - queue
  - widgets
  - presentum

version: 1.0.0+1

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
   generate: true
   uses-material-design: true