name: example
description: "Dynamic, conditional UI example"

publish_to: "none"

homepage: https://github.com/itsezlife/presentum

repository: https://github.com/itsezlife/presentum

issue_tracker: https://github.com/itsezlife/presentum/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - presentation
  - state
  - queue
  - widgets
  - presentum

version: 1.2.0+4

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  ## Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  ## Presentum package
  presentum:
    path: ../

  web: ^1.1.1

  ## Local packages
  shared:
    path: packages/shared
  app_ui:
    path: packages/app_ui
  firebase_remote_config_client:
    path: packages/remote_config_client/firebase_remote_config_client
  remote_config_repository:
    path: packages/remote_config_repository

  ## Storage
  shared_preferences: ^2.5.4

  ## Navigation
  octopus:
    git:
      url: https://github.com/itsezlife/octopus.git
      ref: master

  ## Utilities
  collection: any
  async: any
  meta: any

  ## Layout
  boxy: ^2.2.2

  ## Firebase
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6

  ## Code push
  shorebird_code_push: ^2.0.5
  restart_app: ^1.3.2
  slide_countdown: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  ## Code generation
  build_runner: ^2.10.4
  pubspec_generator: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  assets:
    - shorebird.yaml
  generate: true
  uses-material-design: true

flutter_gen:
  output: lib/src/common/constant/
  line_length: 80
