name: presentum
description: "A declarative cross-platform Flutter engine with focus on state to display presentations, such as campaigns, banners, notifications, etc., anywhere, anytime."
version: 0.3.6

homepage: https://docs.presentum.dev/

repository: https://github.com/itsezlife/presentum

issue_tracker: https://github.com/itsezlife/presentum/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - presentation
  - state
  - queue
  - widgets
  - presentum

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.24.0"

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/firebase_options.dart
  - /example/macos/Runner/GoogleService-Info.plist

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
