name: remote_config_client
description: A pure-dart base remote config client for managing application configuration from remote sources.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0"

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
dependencies:
  equatable: ^2.0.7
